name: Weekly Hub Snapshots Update

on:
  # Run the workflow once a week on Sunday at 05:00 UTC
  schedule:
    - cron: '0 5 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install huggingface_hub
          # Install git-lfs to be able to commit lfs files
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Clone target repo without downloading LFS files
        run: |
          # CRITICAL FIX:
          # GIT_LFS_SKIP_SMUDGE=1 tells git-lfs to NOT download the large files.
          # We get the file structure and git history, but the large files will be
          # tiny pointers, saving massive amounts of disk space and time.
          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/datasets/hfmlsoc/hub_weekly_snapshots target_repo

      - name: Run snapshot generation script
        run: |
          # This script will now run against a lightweight clone of the target repo.
          # os.path.exists() will work correctly on the directory structure.
          python hub_download.py ./target_repo

      - name: Commit and push new snapshots
        working-directory: ./target_repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the token to the remote URL for the push operation
          git remote set-url origin https://huggingface-bot:${HF_TOKEN}@huggingface.co/datasets/hfmlsoc/hub_weekly_snapshots

          ITEMS="daily_papers datasets models spaces"
          PUSH_COUNT=0

          for item in $ITEMS; do
            if [ -d "$item" ]; then
              for week_dir in "$item"/*/; do
                if ! git ls-files --error-unmatch "$week_dir" > /dev/null 2>&1; then
                  echo "New snapshot found: $week_dir. Preparing commit."
                  
                  # IMPORTANT: Track the new files with Git LFS
                  git lfs track "${week_dir}*.parquet"
                  git add .gitattributes
                  git add "$week_dir"
                  
                  dir_name=${week_dir%/}
                  COMMIT_MSG="feat(data): Add ${item} snapshot for week of ${dir_name#$item/}"
                  git commit -m "$COMMIT_MSG"
                  
                  echo "Pushing commit for $week_dir"
                  git push
                  
                  PUSH_COUNT=$((PUSH_COUNT + 1))
                fi
              done
            fi
          done

          if [ $PUSH_COUNT -eq 0 ]; then
            echo "No new weekly snapshots to push."
          else
            echo "Successfully pushed $PUSH_COUNT new snapshot(s)."
          fi