name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Add this to enable manual triggering
permissions:
  actions: write
  contents: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@2.0.10
        with:
          workflow_files: "daily_update.yml,hub_snapshot_update.yml"
          time_elapsed: "0"
