name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Keep repo active
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Last run: $(date)" > .github/keepalive.txt
          git add .github/keepalive.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: keepalive commit" && git push)
